name: Deploy Staging Backend

on:
  push:
    branches:
      - develop
    paths:
      - 'nicsan-crm-backend/**'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::132418765186:role/nicsan-crm-deployer
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nicsan-crm-api
          IMAGE_TAG: staging-${{ github.sha }}
        run: |
          cd nicsan-crm-backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update ECS service
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nicsan-crm-api
          IMAGE_TAG: staging-${{ github.sha }}
        run: |
          # Get current task definition
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition nicsan-backend-task-staging --query taskDefinition)
          
          # Update image in task definition
          NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" '.containerDefinitions[0].image = $IMAGE')
          
          # Remove fields that shouldn't be in new task definition
          NEW_TASK_DEFINITION=$(echo $NEW_TASK_DEFINITION | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)')
          
          # Register new task definition
          aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION"
          
          # Update service
          aws ecs update-service \
            --cluster nicsan-backend-cluster \
            --service nicsan-backend-staging \
            --task-definition nicsan-backend-task-staging

      - name: Wait for deployment to complete
        run: |
          aws ecs wait services-stable \
            --cluster nicsan-backend-cluster \
            --services nicsan-backend-staging

      - name: Test staging backend
        run: |
          # Wait a bit for the service to be ready
          sleep 30
          
          # Test health endpoint
          curl -f https://nicsan-backend-staging-alb-2024475140.ap-south-1.elb.amazonaws.com/health || exit 1
          
          echo "✅ Staging backend deployment successful!"
