name: Deploy Production Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npm run build -- --mode production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3 (prod)
        run: |
          aws s3 sync dist/ s3://nicsan-crm-pdfs/ --delete

      - name: Invalidate CloudFront cache (prod)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3NW822N1SKA1U \
            --paths "/*"
